### ISSUE TITLE
problem with nbextension install

### ISSUE THREAD

**Issue by frankbolton** [nji-syd/fastai-docker#1]
It's great to have a resource for making this much easier than working from scratch!
I'm encountering a problem towards the end of the setup (Host is ubuntu 1604)
Docker version 18.09.3

Step 21/26 : RUN /bin/bash -c "source activate fastai && jupyter contrib nbextension install"
 ---> Running in bb68e517ada7
Error executing Jupyter command 'contrib': [Errno 2] No such file or directory
The command '/bin/sh -c /bin/bash -c "source activate fastai && jupyter contrib nbextension install"' returned a non-zero code: 1

**Comment by nji-syd** [comment]
Hi Frank -- I've posted an update to the files to reflect changes to the Jupyter package. One way around this issue is to install nb_conda_kernels, ipykernel, jupyter, notebook in the base conda environment and ipykernel in the fastai environment. The notebook can then be switched to the fastai environment. Couldn't find a way to set fastai as the default environment.

**Comment by nji-syd** [comment]
If you don't need multiple environments, an easier way is just to install jupyter into the fastai environment and start the notebook server from there. nbextension is in the 0.7 environment but removed from fastai 1.0
